name: JS Actions Workfow

on: [push]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world
        with:
          first-greeting: "Danielle"
      
      - name: Tell me a dumb joke
        uses: ./.github/actions/joke-action